### python数据分析pandas学习2

In [61]:
#读取数据
import numpy as np
import pandas as pd

In [62]:
df = pd.read_excel("douban.xlsx")

In [63]:
df.head(5)

,名字,投票人数,类型,产地,上映时间,时长,年代,评分,首映地点
0,肖申克的救赎,692795.0,剧情/犯罪,美国,1994-09-10 00:00:00,142,1994,9.6,多伦多电影节
1,控方证人,42995.0,剧情/悬疑/犯罪,美国,1957-12-17 00:00:00,116,1957,9.5,美国
2,美丽人生,327855.0,剧情/喜剧/爱情,意大利,1997-12-20 00:00:00,116,1997,9.5,意大利
3,阿甘正传,580897.0,剧情/爱情,美国,1994-06-23 00:00:00,142,1994,9.4,洛杉矶首映
4,霸王别姬,478523.0,剧情/爱情/同性,中国大陆,1993-01-01 00:00:00,171,1993,9.4,香港

### 2.1数据格式转换

In [64]:
#查看数据格式
df.投票人数.dtype
df.名字.dtype

dtype('O')

In [65]:
#数据格式转换
df.投票人数 = df.投票人数.astype("int")

In [66]:
#查看数据类型
df.投票人数.dtype

dtype('int64')

In [67]:
#年份转化为整数格式
# df.年代 = df.年代.astype("int")
#查找数据
df[df.年代 == "2008\u200e"].年代.values

array(['2008\u200e'], dtype=object)

In [72]:
#修改数据
df.loc[14934, "年代"]=2008

In [73]:
# df["年代"]= df["年代"].astype("int")

In [76]:
df.年代[:5]

0    1994
1    1957
2    1997
3    1994
4    1993
Name: 年代, dtype: object

In [92]:
#电影时长转换
df["时长"] = df.时长.astype('int')

In [93]:
# df[df.时长 == '12J']
# df.drop([32949], inplace=True)

In [94]:
# df[df.时长 == '12J']

In [95]:
df.时长.head(5)

0    142
1    116
2    116
3    142
4    171
Name: 时长, dtype: int64

In [96]:
df.head(5)

       名字    投票人数        类型    产地                 上映时间   时长    年代   评分    首映地点
0  肖申克的救赎  692795     剧情/犯罪    美国  1994-09-10 00:00:00  142  1994  9.6  多伦多电影节
1    控方证人   42995  剧情/悬疑/犯罪    美国  1957-12-17 00:00:00  116  1957  9.5      美国
2   美丽人生   327855  剧情/喜剧/爱情   意大利  1997-12-20 00:00:00  116  1997  9.5     意大利
3    阿甘正传  580897     剧情/爱情    美国  1994-06-23 00:00:00  142  1994  9.4   洛杉矶首映
4    霸王别姬  478523  剧情/爱情/同性  中国大陆  1993-01-01 00:00:00  171  1993  9.4      香港

### 2.2排序

In [211]:
#默认排序(按照index进行排序)
df.sort_index()[:5]

       名字    投票人数        类型    产地                 上映时间   时长    年代   评分    首映地点
0  肖申克的救赎  692795     剧情/犯罪    美国  1994-09-10 00:00:00  142  1994  9.6  多伦多电影节
1    控方证人   42995  剧情/悬疑/犯罪    美国  1957-12-17 00:00:00  116  1957  9.5      美国
2   美丽人生   327855  剧情/喜剧/爱情   意大利  1997-12-20 00:00:00  116  1997  9.5     意大利
3    阿甘正传  580897     剧情/爱情    美国  1994-06-23 00:00:00  142  1994  9.4   洛杉矶首映
4    霸王别姬  478523  剧情/爱情/同性  中国大陆  1993-01-01 00:00:00  171  1993  9.4      香港

In [103]:
#特定列排序
df.sort_values(by="投票人数",ascending=False)[:5]

,名字,投票人数,类型,产地,上映时间,时长,年代,评分,首映地点
0,肖申克的救赎,692795,剧情/犯罪,美国,1994-09-10 00:00:00,142,1994,9.6,多伦多电影节
9,这个杀手不太冷,662552,剧情/动作/犯罪,法国,1994-09-14 00:00:00,133,1994,9.4,法国
22,盗梦空间,642134,剧情/动作/科幻/悬疑/冒险,美国,2010-09-01 00:00:00,148,2010,9.2,中国大陆
3,阿甘正传,580897,剧情/爱情,美国,1994-06-23 00:00:00,142,1994,9.4,洛杉矶首映
99,三傻大闹宝莱坞,549808,剧情/喜剧/爱情/歌舞,印度,2011-12-08 00:00:00,171,2009,9.1,中国大陆

In [106]:
df.评分.dtype

dtype('float64')

In [212]:
#按照主评分排序, 副 年代(依照评分为主线, 投票人数为辅线)
df.sort_values(by=["评分", "投票人数"], ascending=False)[:5]

,名字,投票人数,类型,产地,上映时间,时长,年代,评分,首映地点
9278,平安结祈 平安結,208,音乐,日本,2012-02-24 00:00:00,60,2012,9.9,美国
13882,武之舞,128,纪录片,中国大陆,1997-02-01 00:00:00,60,34943,9.9,美国
1110,NaN,76,科幻/纪录片,美国,1905-06-23 00:00:00,75,2001,9.9,美国
23554,未作回答的问题：伯恩斯坦哈佛六讲,61,纪录片,美国,1905-05-29 00:00:00,60,1973,9.9,美国
35463,NaN,46,纪录片/音乐,韩国,2013-10-31 00:00:00,90,2013,9.9,韩国

### 2.3基本统计分析

In [116]:
#描述性统计(描述数值型数据的方式)
df.describe()

                投票人数            时长            评分
count   38736.000000  38736.000000  38736.000000
mean     6186.150764     89.051761      6.935649
std     26144.156471     83.334169      1.270110
min      -118.000000      1.000000      2.000000
25%        98.000000     60.000000      6.300000
50%       341.000000     92.000000      7.100000
75%      1740.250000    106.000000      7.800000
max    692795.000000  11500.000000      9.900000

In [131]:
#挑出数据
df[df.投票人数 < 10]
df.drop(df[df.投票人数<10].index, inplace=True)#使用inplace进行数据覆盖
# df.drop([19777, 19786, 19797], inplace=True)

In [132]:
df[df.投票人数 < 10]

Empty DataFrame
Columns: [名字, 投票人数, 类型, 产地, 上映时间, 时长, 年代, 评分, 首映地点]
Index: []

In [133]:
df.describe()

                投票人数            时长            评分
count   38731.000000  38731.000000  38731.000000
mean     6186.956211     89.052026      6.935633
std     26145.747884     83.338929      1.270169
min        12.000000      1.000000      2.000000
25%        98.000000     60.000000      6.300000
50%       341.000000     92.000000      7.100000
75%      1741.000000    106.000000      7.800000
max    692795.000000  11500.000000      9.900000

In [136]:
#重新排序inde
df.index = range(len(df))

In [138]:
#均值
df.评分.mean()

6.935632955513599

In [139]:
#最大值
df.评分.max()

9.9

In [140]:
#标准差
df.投票人数.std()

26145.747884444205

In [141]:
#描述数据(非数值数据的统计)
df.名字.describe(include="object")

count     38171
unique    35546
top       周六夜现场
freq         78
Name: 名字, dtype: object

In [142]:
#求和
df.评分.sum()

268624.0

In [213]:
#相关系数和协方差
df[["评分",'投票人数']].corr()#协方差数据的统计

            评分      投票人数
评分    1.000000  0.122901
投票人数  0.122901  1.000000

In [150]:
#计数
df.产地.unique()

array(['美国', '意大利', '中国大陆', '日本', '法国', '英国', '韩国', '中国香港', '阿根廷', '德国',
       '印度', '其他', '加拿大', '波兰', '泰国', '澳大利亚', '西班牙', '俄罗斯', '中国台湾', '荷兰',
       '丹麦', '比利时', 'USA', '苏联', '墨西哥', '巴西', '瑞典', '西德'], dtype=object)

In [151]:
len(df.产地.unique())

28

In [154]:
#数据替换
df.产地.replace('USA', "美国", inplace=True)

In [156]:
df.产地.unique()

array(['美国', '意大利', '中国大陆', '日本', '法国', '英国', '韩国', '中国香港', '阿根廷', '德国',
       '印度', '其他', '加拿大', '波兰', '泰国', '澳大利亚', '西班牙', '俄罗斯', '中国台湾', '荷兰',
       '丹麦', '比利时', '苏联', '墨西哥', '巴西', '瑞典', '西德'], dtype=object)

In [159]:
len(df.产地.unique())

25

In [161]:
df.产地.replace(['西德', '苏联'], ['德国', '俄罗斯'], inplace=True)

In [168]:
df.产地.value_counts()[:5]

美国      11979
日本       5050
中国大陆     3803
中国香港     2851
法国       2816
Name: 产地, dtype: int64

In [167]:
#年代的操作
df.年代.value_counts()[:5]

2012    2042
2013    2001
2008    1963
2014    1887
2010    1885
Name: 年代, dtype: int64

In [164]:
#保存数据
df.to_excel("doubanpro2.xlsx")

### 2.4 数据透视

In [174]:
#查看所有数据
pd.set_option('max_columns', 100)
pd.set_option('max_rows', 500)

In [175]:
#1.基本形式
pd.pivot_table(df, index=["年代"])#指定年代来来进行数据分析,计算平均数

               投票人数          时长        评分
年代
1888     388.000000   60.000000  7.950000
1890      51.000000   60.000000  4.800000
1892     176.000000   60.000000  7.500000
1894     112.666667   60.000000  6.633333
1895     959.875000   60.000000  7.575000
1896     984.250000   60.000000  7.037500
1897      67.000000   60.000000  6.633333
1898     578.500000   60.000000  7.450000
1899      71.000000    9.500000  6.900000
1900     175.285714   36.714286  7.228571
1901     164.500000   47.250000  7.250000
1902    1934.166667   34.666667  7.483333
1903     295.625000   29.625000  6.968750
1904     195.875000   41.250000  7.212500
1905     332.600000   43.800000  6.820000
1906     189.857143   30.571429  7.342857
1907     213.600000   31.800000  7.020000
1908     258.833333   34.166667  7.150000
1909      58.600000   20.600000  7.560000
1910     105.200000   41.800000  6.940000
1911     240.000000   25.750000  7.375000
1912     152.200000   16.400000  7.920000
1913      66.125000   57.750000  6.862500
1914     104.923077   25.923077  6.473077
1915     314.900000   56.800000  7.260000
1916     613.666667   43.833333  7.758333
1917     124.416667   31.333333  7.075000
1918     357.083333   35.166667  7.200000
1919     179.850000   62.400000  7.490000
1920     636.500000   59.357143  7.492857
1921     729.818182   57.363636  7.750000
1922     767.090909   66.363636  7.804545
1923     426.000000   74.055556  7.883333
1924     371.785714   81.178571  8.053571
1925    1104.280000   84.440000  7.788000
1926     443.608696   80.304348  7.773913
1927     695.275862   87.241379  7.751724
1928     404.825000   71.775000  7.945000
1929     740.542857   69.371429  7.440000
1930     555.080000   74.160000  7.360000
1931    1468.666667   78.523810  7.483333
1932     600.081081   77.540541  7.294595
1933     729.720000   76.360000  7.430000
1934     776.490196   83.196078  7.519608
1935     887.695652   73.673913  7.515217
1936    1465.466667   76.266667  7.635000
1937    1549.700000  313.800000  7.582000
1938     552.000000   85.973684  7.736842
1939    5911.857143   97.387755  7.520408
1940    5548.743590   92.820513  7.571795
1941    1552.808511   89.127660  7.427660
1942    2607.754717   78.264151  7.554717
1943     742.842105   78.456140  7.615789
1944    1007.370370   81.925926  7.538889
1945     989.020408   86.959184  7.673469
1946    1034.457627   85.016949  7.606780
1947     439.400000   87.120000  7.453333
1948    1186.505747   88.206897  7.657471
1949     641.685393   81.988764  7.646067
1950    2235.026316   80.157895  7.655263
1951     956.101266   85.632911  7.636709
1952    1473.540230   81.528736  7.743678
1953    4786.113636   84.170455  7.567045
1954    2180.245098   85.549020  7.702941
1955    1983.739130   83.669565  7.580000
1956    1054.605442   76.408163  7.600000
1957    2973.579439   87.355140  7.652336
1958     886.196721   82.975410  7.536885
1959    1725.070312   90.070312  7.571875
1960    1446.274809  101.312977  7.569466
1961    3186.833333   98.215686  7.744118
1962    1972.118881   91.615385  7.704895
1963    1184.027972   92.020979  7.536364
1964    1107.763736   89.714286  7.523077
1965    1988.184049   90.478528  7.576074
1966    1319.525140   89.486034  7.518994
1967    1237.289773   91.590909  7.484659
1968    1096.220930   91.744186  7.317442
1969     593.111111   98.666667  7.370048
1970     676.789474   96.973684  7.291053
1971    1368.506849   96.315068  7.155708
1972    2299.096618   96.289855  7.268116
1973     800.103286   94.882629  7.250235
1974    1685.789238   95.318386  7.062332
1975    2222.739796   97.566327  7.071429
1976    1340.618026   95.055794  7.107725
1977     961.461187   98.022831  7.150685
1978    1001.820896   94.467662  7.096517
1979    1878.621145   96.000000  7.296035
1980    2407.683036   94.178571  7.186607
1981    1609.062044   93.321168  7.157299
1982    2142.729323   91.984962  7.297368
1983    1541.191336   92.169675  7.310108
1984    2667.173469   90.918367  7.375170
1985    1593.043750   93.659375  7.280312
1986    2819.913846  117.178462  7.261231
1987    3128.775510   88.938776  7.284548
1988    4800.227621   88.859335  7.265729
1989    2994.417303   88.458015  7.210687
1990    4965.587786   91.882952  7.149109
1991    4685.819512   93.370732  7.154634
1992    5486.133333   92.572414  7.223678
1993    8117.759637   95.269841  7.195692
1994   11479.255061   91.344130  7.262348
1995    8132.605317   94.441718  7.289366
1996    5095.883946   95.243714  7.258801
1997    8243.938547   94.970205  7.330168
1998    7431.790295   91.131716  7.238302
1999    7137.049600   92.457600  7.188000
2000    5907.770178   92.191518  7.134063
2001    8489.757246   90.958937  7.110145
2002    6552.593333   91.584444  7.069778
2003    7891.964248   90.558360  7.137750
2004    8587.632599   90.424670  7.031366
2005    6506.110847   92.080760  7.030008
2006    7278.260726   90.144554  6.914719
2007    6253.837522   86.628288  6.875102
2008    6757.133979   85.151299  6.913194
2009    8716.364662   86.384533  6.750000
2010    9574.788329   83.421751  6.769867
2011    8763.110397   84.125938  6.577010
2012    7082.787463   85.099902  6.458374
2013    7603.723138   84.902049  6.392604
2014    7723.302597   85.997880  6.259777
2015    7841.408291   89.863693  6.141960
2016    7176.019380   91.329457  5.868217
34943    128.000000   60.000000  9.900000
39180     49.000000  109.000000  8.900000
2008‎    544.000000   93.000000  2.700000

In [214]:
#2.多个索引(默认平均值)
pd.pivot_table(df, index=["年代", '产地'], values=["投票人数"],)

                    投票人数
年代    产地
1888  英国      388.000000
1890  美国       51.000000
1892  法国      176.000000
1894  法国      148.000000
      美国       95.000000
1895  法国      959.875000
1896  法国     1874.250000
      美国       55.666667
      英国      210.000000
1897  法国       67.000000
1898  法国      991.000000
      英国      166.000000
1899  法国       71.000000
1900  法国       52.000000
      美国      212.500000
      英国      323.000000
1901  法国      142.000000
      英国      172.000000
1902  法国     3818.000000
      美国       50.333333
1903  法国       81.600000
      美国      824.500000
      英国      308.000000
1904  法国      217.714286
      美国       43.000000
1905  中国大陆    137.000000
      美国       45.666667
      英国     1389.000000
1906  意大利      37.000000
      法国       77.333333
      美国      425.500000
      英国      209.000000
1907  法国      213.600000
1908  法国      458.666667
      美国       33.500000
      西班牙     110.000000
1909  美国       58.600000
1910  法国       78.666667
      美国      145.000000
1911  意大利     297.000000
      美国      299.000000
      荷兰       65.000000
1912  俄罗斯     511.000000
      法国       71.500000
      美国       53.500000
1913  俄罗斯      54.000000
      德国      108.000000
      意大利      42.000000
      法国       40.000000
      瑞典       48.000000
      美国       79.000000
1914  意大利     204.000000
      法国       31.000000
      美国      103.875000
1915  俄罗斯      41.000000
      意大利     134.000000
      法国       89.500000
      美国      371.500000
1916  德国       48.000000
      美国      665.090909
1917  俄罗斯      86.000000
      德国       46.000000
      瑞典       46.000000
      美国      146.111111
1918  德国      190.000000
      瑞典       30.000000
      美国      406.500000
1919  丹麦       57.000000
      德国      118.000000
      法国       76.000000
      美国      239.818182
1920  其他       56.000000
      德国     1514.750000
      美国      310.666667
1921  丹麦       91.000000
      德国      129.600000
      法国       55.000000
      瑞典      804.000000
      美国     1107.923077
1922  中国大陆   1600.000000
      丹麦      343.500000
      德国      963.000000
      美国      698.142857
1923  中国大陆     41.000000
      俄罗斯      54.000000
      德国       68.000000
      法国      157.500000
      美国      681.800000
      英国       57.000000
1924  俄罗斯      94.666667
      德国      463.750000
      法国      161.600000
      美国      539.500000
      英国      106.500000
1925  丹麦       87.000000
      俄罗斯     283.000000
      其他     8835.000000
      德国      212.333333
      日本       77.000000
      法国      137.250000
      美国     1391.000000
      英国      164.000000
1926  中国大陆     84.000000
      俄罗斯     193.000000
      德国      612.400000
      日本      314.000000
      法国      114.500000
      美国      634.000000
1927  中国大陆    366.000000
      俄罗斯      49.000000
      德国     5251.000000
      法国      127.000000
      美国      472.357143
      英国      511.333333
1928  中国大陆     69.000000
      俄罗斯     239.500000
      其他       40.000000
      德国      172.250000
      法国      609.857143
      美国      471.200000
      英国      229.250000
      荷兰      306.000000
1929  中国大陆     64.500000
      俄罗斯    1851.333333
      其他       72.000000
      德国      390.000000
      日本      126.400000
      比利时      37.000000
      法国     4356.333333
      瑞典       32.000000
      美国      230.625000
      英国      239.800000
      荷兰     1400.000000
1930  俄罗斯     217.000000
      德国      651.500000
      日本       73.200000
      法国      725.833333
      美国      735.100000
      英国      285.000000
1931  中国大陆    870.000000
      俄罗斯      41.000000
      其他       63.000000
      墨西哥     115.000000
      巴西       69.000000
      德国     2910.600000
      日本      399.833333
      法国      288.200000
      美国     2395.823529
      英国      239.500000
      荷兰       55.000000
1932  中国大陆    153.000000
      俄罗斯      33.000000
      德国      318.666667
      日本      797.000000
      法国      149.666667
      美国      726.640000
      英国       55.000000
1933  中国大陆    250.000000
      其他      227.000000
      德国      231.750000
      日本      142.125000
      比利时      89.000000
      法国      679.000000
      美国     1116.259259
      英国      158.000000
      西班牙     772.000000
1934  中国大陆   1434.857143
      俄罗斯     122.000000
      意大利      90.500000
      日本      218.000000
      法国      287.428571
      美国     1110.681818
      英国      313.750000
1935  中国大陆    412.500000
      中国香港    101.000000
      德国     3393.333333
      日本      199.333333
      法国      176.500000
      美国      652.250000
      英国     4545.500000
1936  中国大陆    223.500000
      墨西哥      42.000000
      日本      420.428571
      法国      273.125000
      瑞典       76.000000
      美国     2302.676471
      英国      699.400000
1937  中国大陆   3356.500000
      俄罗斯     304.500000
      日本      278.250000
      法国     1123.750000
      美国     1851.866667
      英国      381.000000
1938  中国大陆     49.000000
      中国香港     39.000000
      俄罗斯     179.000000
      德国     1209.000000
      日本      102.000000
      法国      301.400000
      美国      537.285714
      英国     1279.500000
1939  中国大陆    129.500000
      中国香港     47.000000
      俄罗斯     458.000000
      日本      403.250000
      法国     1946.000000
      美国     8290.088235
      英国      272.750000
1940  中国大陆    703.000000
      俄罗斯      72.000000
      德国       36.000000
      日本       50.000000
      瑞典       38.000000
      美国     7135.466667
      英国      359.500000
1941  中国大陆   1013.000000
      日本      340.000000
      法国       35.000000
      美国     1829.081081
      英国      628.333333
1942  丹麦       33.000000
      俄罗斯      98.000000
      日本      516.666667
      法国      151.000000
      美国     3162.813953
      英国       75.666667
1943  中国大陆     83.000000
      丹麦      765.000000
      德国       74.500000
      意大利     373.000000
      日本      613.500000
      法国      515.666667
      美国      857.414634
      英国      270.000000
1944  俄罗斯     808.000000
      墨西哥      38.000000
      德国      108.000000
      意大利     631.000000
      日本       61.750000
      法国       37.000000
      瑞典      304.000000
      美国     1319.410256
      英国      153.600000
1945  意大利    3062.000000
      日本      651.750000
      法国      953.666667
      美国      956.222222
      英国     1101.600000
1946  丹麦       43.000000
      其他       64.000000
...                  ...
2006  法国     3991.175926
      波兰      338.000000
      泰国     3005.086957
      澳大利亚   5965.727273
      瑞典      561.500000
      美国     9606.865234
      英国     4831.505155
      荷兰     4836.125000
      西班牙    6999.850000
      阿根廷     271.000000
      韩国     7454.670455
2007  中国台湾  19848.000000
      中国大陆  10014.552846
      中国香港  17804.468085
      丹麦      198.750000
      俄罗斯    2119.037037
      其他     1275.905660
      加拿大    1131.338983
      印度     3136.818182
      墨西哥     807.000000
      巴西     3170.444444
      德国     1260.814815
      意大利     751.733333
      日本     4331.866667
      比利时    1454.500000
      法国     3424.101695
      波兰     3409.400000
      泰国     8888.192308
      澳大利亚   1244.200000
      瑞典     1526.800000
      美国     8535.287215
      英国     7168.522523
      荷兰      344.857143
      西班牙    5072.708333
      阿根廷     250.166667
      韩国     3769.526316
2008  中国台湾  12214.971429
      中国大陆  12444.786207
      中国香港  16116.178571
      丹麦      367.812500
      俄罗斯     625.166667
      其他      865.840000
      加拿大     820.819672
      印度     2551.476190
      墨西哥     274.333333
      巴西      716.142857
      德国     3337.485714
      意大利    2109.545455
      日本     5742.048387
      比利时    1587.166667
      法国     3308.900000
      波兰      888.500000
      泰国     5840.950000
      澳大利亚   4784.409091
      瑞典     5162.444444
      美国     8288.034226
      英国     8321.210145
      荷兰      638.769231
      西班牙    8426.090909
      阿根廷    4315.000000
      韩国     6816.720000
2009  中国台湾  17568.727273
      中国大陆  12499.034884
      中国香港  22658.319149
      丹麦     1412.363636
      俄罗斯    1046.857143
      其他     1036.009091
      加拿大    4876.465116
      印度    22459.280000
      墨西哥     934.800000
      巴西     1517.666667
      德国     1655.365385
      意大利     958.956522
      日本     3422.120000
      比利时     980.000000
      法国     4826.124031
      波兰      286.461538
      泰国     8631.125000
      澳大利亚   9026.538462
      瑞典      920.700000
      美国    13008.017915
      英国     7865.020690
      荷兰     2216.272727
      西班牙    4439.583333
      阿根廷    7434.000000
      韩国     4688.767123
2010  中国台湾  21248.269231
      中国大陆  14713.879518
      中国香港  44322.022727
      丹麦     2678.250000
      俄罗斯     880.647059
      其他     1083.688679
      加拿大    1700.066667
      印度     2345.096774
      墨西哥    3973.666667
      巴西    10777.600000
      德国     2390.561404
      意大利    1157.000000
      日本     4939.560811
      比利时     934.800000
      法国     3543.600000
      波兰      336.500000
      泰国    18438.096774
      澳大利亚   1994.294118
      瑞典     1361.166667
      美国    13966.230620
      英国     5014.580645
      荷兰      478.100000
      西班牙    3357.366667
      阿根廷     177.500000
      韩国     8570.764045
2011  中国台湾  16625.022727
      中国大陆  11704.157729
      中国香港  27313.710526
      丹麦     2550.500000
      俄罗斯     482.600000
      其他     3843.293333
      加拿大     764.361111
      印度      630.700000
      墨西哥     273.000000
      巴西      787.333333
      德国     1480.925000
      意大利     611.750000
      日本     3174.931741
      比利时    2836.875000
      法国     5638.576577
      波兰      769.555556
      泰国     1717.458333
      澳大利亚   4037.461538
      瑞典     1916.333333
      美国    13534.009560
      英国     4485.156716
      荷兰      331.666667
      西班牙   12269.857143
      阿根廷    2010.000000
      韩国     8949.400000
2012  中国台湾  10831.804878
      中国大陆   8776.529551
      中国香港  19000.921053
      丹麦     6043.812500
      俄罗斯     785.363636
      其他     1086.935780
      加拿大    3079.214286
      印度     2414.394737
      墨西哥     286.500000
      巴西      399.000000
      德国     6875.442308
      意大利     701.555556
      日本     2697.934256
      比利时     598.125000
      法国     3332.616071
      波兰      120.000000
      泰国     2492.481481
      澳大利亚   1317.642857
      瑞典      827.625000
      美国    12299.159844
      英国     3793.068966
      荷兰      318.111111
      西班牙    4086.333333
      阿根廷      84.333333
      韩国     5762.537736
2013  中国台湾   3354.882353
      中国大陆  12229.840796
      中国香港  11841.742857
      丹麦     5986.555556
      俄罗斯    1793.000000
      其他      789.440476
      加拿大    1242.242424
      印度      738.444444
      墨西哥    2532.666667
      巴西     2479.666667
      德国     1586.822222
      意大利    4140.133333
      日本     3029.111111
      比利时     883.285714
      法国     3471.741573
      波兰     1682.333333
      泰国     1238.040000
      澳大利亚  15851.866667
      瑞典      752.444444
      美国    11493.405904
      英国     3295.288591
      荷兰      749.000000
      西班牙    1894.708333
      阿根廷    1056.833333
      韩国    10189.036036
2014  中国台湾   3536.222222
      中国大陆  12461.264550
      中国香港  12444.023810
      丹麦      698.800000
      俄罗斯    2997.875000
      其他     2012.212500
      加拿大    2456.217391
      印度     4253.322581
      墨西哥    1066.000000
      巴西     3343.000000
      德国     2675.333333
      意大利     798.500000
      日本     2849.774481
      比利时    2260.000000
      法国     6754.428571
      波兰      681.000000
      泰国      856.035714
      澳大利亚   8049.562500
      瑞典     4062.600000
      美国    10662.456311
      英国     9672.163462
      荷兰     1643.500000
      西班牙    1832.437500
      阿根廷   19776.750000
      韩国     3776.266667
2015  中国台湾  13974.760000
      中国大陆  14379.621622
      中国香港  14385.648649
      丹麦     1729.000000
      俄罗斯    9391.428571
      其他     3333.392857
      加拿大     689.937500
      印度     2853.090909
      墨西哥    5352.250000
      巴西      501.400000
      德国     1501.772727
      意大利    7022.875000
      日本     2301.793478
      比利时    7121.333333
      法国     2753.233333
      波兰      165.000000
      泰国      744.333333
      澳大利亚  12964.533333
      瑞典     4455.500000
      美国     9194.213592
      英国     7049.764045
      荷兰      696.428571
      西班牙    1060.928571
      阿根廷     124.333333
      韩国     3209.247706
2016  中国大陆   8604.280000
      中国香港   6755.363636
      丹麦       43.000000
      其他      185.750000
      加拿大     347.500000
      印度      317.000000
      日本      579.763158
      法国       39.000000
      美国    10563.848485
      英国    14607.272727
      韩国     1739.850000
34943 中国大陆    128.000000
39180 日本       49.000000
2008‎ 中国大陆    544.000000

[1587 rows x 1 columns]

In [180]:
#4.指定特定函数
pd.pivot_table(df, index=['年代', '产地'], values=["投票人数"], aggfunc=np.sum)

               投票人数
年代    产地
1888  英国        776
1890  美国         51
1892  法国        176
1894  法国        148
      美国        190
1895  法国       7679
1896  法国       7497
      美国        167
      英国        210
1897  法国        201
1898  法国        991
      英国        166
1899  法国        142
1900  法国        156
      美国        425
      英国        646
1901  法国        142
      英国        516
1902  法国      11454
      美国        151
1903  法国        816
      美国       3298
      英国        616
1904  法国       1524
      美国         43
1905  中国大陆      137
      美国        137
      英国       1389
1906  意大利        37
      法国        232
      美国        851
      英国        209
1907  法国       1068
1908  法国       1376
      美国         67
      西班牙       110
1909  美国        293
1910  法国        236
      美国        290
1911  意大利       297
      美国        598
      荷兰         65
1912  俄罗斯       511
      法国        143
      美国        107
1913  俄罗斯        54
      德国        108
      意大利        42
      法国         40
      瑞典         48
      美国        237
1914  意大利       204
      法国         31
      美国       2493
1915  俄罗斯        41
      意大利       134
      法国        179
      美国       5944
1916  德国         48
      美国       7316
1917  俄罗斯        86
      德国         46
      瑞典         46
      美国       1315
1918  德国        190
      瑞典         30
      美国       4065
1919  丹麦         57
      德国        826
      法国         76
      美国       2638
1920  其他         56
      德国       6059
      美国       2796
1921  丹麦         91
      德国        648
      法国        110
      瑞典        804
      美国      14403
1922  中国大陆     1600
      丹麦        687
      德国       4815
      美国       9774
1923  中国大陆       41
      俄罗斯        54
      德国         68
      法国        630
      美国       6818
      英国         57
1924  俄罗斯       284
      德国       3710
      法国        808
      美国       5395
      英国        213
1925  丹麦         87
      俄罗斯       566
      其他       8835
      德国        637
      日本         77
      法国        549
      美国      16692
      英国        164
1926  中国大陆       84
      俄罗斯       579
      德国       3062
      日本        314
      法国        458
      美国       5706
1927  中国大陆      732
      俄罗斯       147
      德国      10502
      法国        635
      美国       6613
      英国       1534
1928  中国大陆       69
      俄罗斯       479
      其他         40
      德国        689
      法国       4269
      美国       9424
      英国        917
      荷兰        306
1929  中国大陆      129
      俄罗斯      5554
      其他         72
      德国       1950
      日本        632
      比利时        37
      法国      13069
      瑞典         32
      美国       1845
      英国       1199
      荷兰       1400
1930  俄罗斯       217
      德国       1303
      日本        366
      法国       4355
      美国       7351
      英国        285
1931  中国大陆     1740
      俄罗斯        41
      其他         63
      墨西哥       115
      巴西         69
      德国      14553
      日本       2399
      法国       1441
      美国      40729
      英国        479
      荷兰         55
1932  中国大陆      153
      俄罗斯        33
      德国        956
      日本       2391
      法国        449
      美国      18166
      英国         55
1933  中国大陆     1000
      其他        227
      德国        927
      日本       1137
      比利时        89
      法国       2037
      美国      30139
      英国        158
      西班牙       772
1934  中国大陆    10044
      俄罗斯       366
      意大利       181
      日本       1308
      法国       2012
      美国      24435
      英国       1255
1935  中国大陆     1650
      中国香港      101
      德国      10180
      日本       1196
      法国        353
      美国      18263
      英国       9091
1936  中国大陆      894
      墨西哥        42
      日本       2943
      法国       2185
      瑞典         76
      美国      78291
      英国       3497
1937  中国大陆    13426
      俄罗斯       609
      日本       1113
      法国       4495
      美国      55556
      英国       2286
1938  中国大陆       49
      中国香港       39
      俄罗斯       358
      德国       2418
      日本        204
      法国       1507
      美国      11283
      英国       5118
1939  中国大陆      259
      中国香港       47
      俄罗斯       916
      日本       1613
      法国       3892
      美国     281863
      英国       1091
1940  中国大陆      703
      俄罗斯        72
      德国         36
      日本         50
      瑞典         38
      美国     214064
      英国       1438
1941  中国大陆     2026
      日本       1360
      法国         35
      美国      67676
      英国       1885
1942  丹麦         33
      俄罗斯        98
      日本       1550
      法国        302
      美国     136001
      英国        227
1943  中国大陆       83
      丹麦        765
      德国        149
      意大利       373
      日本       2454
      法国       3094
      美国      35154
      英国        270
1944  俄罗斯       808
      墨西哥        38
      德国        108
      意大利       631
      日本        247
      法国         37
      瑞典        304
      美国      51457
      英国        768
1945  意大利      3062
      日本       2607
      法国       2861
      美国      34424
      英国       5508
1946  丹麦         43
      其他         64
...             ...
2006  法国     431047
      波兰        338
      泰国      69117
      澳大利亚    65623
      瑞典       3369
      美国    4918715
      英国     468656
      荷兰      38689
      西班牙    139997
      阿根廷      1897
      韩国     656011
2007  中国台湾   377112
      中国大陆  1231790
      中国香港   836810
      丹麦       2385
      俄罗斯     57214
      其他     135246
      加拿大     66749
      印度      69010
      墨西哥      4842
      巴西      28534
      德国      68084
      意大利     11276
      日本    1039648
      比利时     11636
      法国     404044
      波兰      17047
      泰国     231093
      澳大利亚    18663
      瑞典       7634
      美国    4873649
      英国     795706
      荷兰       2414
      西班牙    121745
      阿根廷      1501
      韩国     286484
2008  中国台湾   427524
      中国大陆  1804494
      中国香港   902506
      丹麦       5885
      俄罗斯     15004
      其他     108230
      加拿大     50070
      印度      53581
      墨西哥      3292
      巴西       5013
      德国     233624
      意大利     46410
      日本    1424028
      比利时      9523
      法国     430157
      波兰       1777
      泰国     116819
      澳大利亚   105257
      瑞典      46462
      美国    5569559
      英国    1148327
      荷兰       8304
      西班牙    185374
      阿根廷     51780
      韩国     511254
2009  中国台湾   386512
      中国大陆  2149834
      中国香港  1064941
      丹麦      15536
      俄罗斯     14656
      其他     113961
      加拿大    209688
      印度     561482
      墨西哥      4674
      巴西       9106
      德国      86079
      意大利     22056
      日本     855530
      比利时      5880
      法国     622570
      波兰       3724
      泰国     207147
      澳大利亚   234690
      瑞典       9207
      美国    7986923
      英国    1140428
      荷兰      24379
      西班牙    106550
      阿根廷     52038
      韩国     342280
2010  中国台湾   552455
      中国大陆  3663756
      中国香港  1950169
      丹麦      21426
      俄罗斯     14971
      其他     114871
      加拿大     51002
      印度      72698
      墨西哥     11921
      巴西      53888
      德国     136262
      意大利     19669
      日本    1462110
      比利时      4674
      法国     442950
      波兰       1346
      泰国     571581
      澳大利亚    33903
      瑞典      16334
      美国    7206575
      英国     777260
      荷兰       4781
      西班牙    100721
      阿根廷       355
      韩国     762798
2011  中国台湾   731501
      中国大陆  3710218
      中国香港  1037921
      丹麦      15303
      俄罗斯      4826
      其他     288247
      加拿大     27517
      印度      18921
      墨西哥      1092
      巴西       4724
      德国      59237
      意大利      9788
      日本     930255
      比利时     22695
      法国     625882
      波兰       6926
      泰国      41219
      澳大利亚    52487
      瑞典       5749
      美国    7078287
      英国     601011
      荷兰       2985
      西班牙    257667
      阿根廷     12060
      韩国     805446
2012  中国台湾   444104
      中国大陆  3712472
      中国香港   722035
      丹麦      96701
      俄罗斯      8639
      其他     118476
      加拿大     86218
      印度      91747
      墨西哥       573
      巴西       1995
      德国     357523
      意大利     12628
      日本     779703
      比利时      4785
      法国     373253
      波兰        360
      泰国      67297
      澳大利亚    18447
      瑞典       6621
      美国    6309469
      英国     549995
      荷兰       2863
      西班牙     85813
      阿根廷       506
      韩国     610829
2013  中国台湾   114066
      中国大陆  4916396
      中国香港   414461
      丹麦      53879
      俄罗斯     14344
      其他      66313
      加拿大     40994
      印度      26584
      墨西哥     15196
      巴西       7439
      德国      71407
      意大利     62102
      日本     899646
      比利时      6183
      法国     308985
      波兰      10094
      泰国      30951
      澳大利亚   237778
      瑞典       6772
      美国    6229426
      英国     490998
      荷兰       8239
      西班牙     45473
      阿根廷      6341
      韩国    1130983
2014  中国台湾    95478
      中国大陆  4710358
      中国香港   522649
      丹麦       3494
      俄罗斯     23983
      其他     160977
      加拿大     56493
      印度     131853
      墨西哥      2132
      巴西      16715
      德国     104338
      意大利      6388
      日本     960374
      比利时     13560
      法国     520091
      波兰       3405
      泰国      23969
      澳大利亚   128793
      瑞典      20313
      美国    5491165
      英国    1005905
      荷兰       9861
      西班牙     29319
      阿根廷     79107
      韩国     453152
2015  中国台湾   349369
      中国大陆  5320460
      中国香港   532269
      丹麦      10374
      俄罗斯     65740
      其他     186670
      加拿大     11039
      印度      62768
      墨西哥     21409
      巴西       2507
      德国      33039
      意大利     56183
      日本     635295
      比利时     21364
      法国     165194
      波兰        660
      泰国      11165
      澳大利亚   194468
      瑞典      17822
      美国    3788016
      英国     627429
      荷兰       4875
      西班牙     14853
      阿根廷       746
      韩国     349808
2016  中国大陆   860428
      中国香港    74309
      丹麦         43
      其他        743
      加拿大       695
      印度        317
      日本      22031
      法国        156
      美国     697214
      英国     160680
      韩国      34797
34943 中国大陆      128
39180 日本         49
2008‎ 中国大陆      544

[1587 rows x 1 columns]

In [181]:
#多函数统计
pd.pivot_table(df, index=["产地"], values=["投票人数", "评分"], aggfunc=[np.sum, np.mean])

            sum                   mean
           投票人数       评分          投票人数        评分
产地
中国台湾    5237466   4367.2   8474.864078  7.066667
中国大陆   41435441  23067.9  10895.461741  6.065711
中国香港   23285389  18457.7   8167.446159  6.474114
丹麦       394784   1434.7   1993.858586  7.245960
俄罗斯      486127   3603.5   1019.134172  7.554507
其他      3054119  13895.9   1590.686979  7.237448
加拿大     1384765   4868.4   1915.304288  6.733610
印度      1146271   2453.4   3210.843137  6.872269
墨西哥      139613    843.4   1173.218487  7.087395
巴西       357136    733.5   3536.000000  7.262376
德国      2680983   7428.4   2597.851744  7.198062
意大利     2502215   5377.3   3340.740988  7.179306
日本     18000703  36334.9   3564.495644  7.195030
比利时      170987   1003.3   1230.122302  7.217986
法国     10213966  20384.7   3627.118608  7.238885
波兰       159577   1347.0    881.640884  7.441989
泰国      1564881   1796.1   5322.724490  6.109184
澳大利亚    1415713   2093.4   4719.043333  6.978000
瑞典       290113   1432.0   1503.176166  7.419689
美国    101806270  83217.4   8498.728608  6.946940
英国     13249562  20789.4   4797.089790  7.526937
荷兰       144836   1114.5    934.425806  7.190323
西班牙     1486733   3139.9   3326.024609  7.024385
阿根廷      258271    843.7   2226.474138  7.273276
韩国      8761080   8596.4   6484.885270  6.362990

In [182]:
#非数值处理, 使用fill_value使得nan为特定值
pd.pivot_table(df, index=["产地"], aggfunc=[np.sum, np.mean], fill_value=0)

            sum                            mean
           投票人数       时长       评分          投票人数          时长        评分
产地
中国台湾    5237466    53925   4367.2   8474.864078   87.257282  7.066667
中国大陆   41435441   309668  23067.9  10895.461741   81.427294  6.065711
中国香港   23285389   252431  18457.7   8167.446159   88.541214  6.474114
丹麦       394784    17444   1434.7   1993.858586   88.101010  7.245960
俄罗斯      486127    45753   3603.5   1019.134172   95.918239  7.554507
其他      3054119   167168  13895.9   1590.686979   87.066667  7.237448
加拿大     1384765    57919   4868.4   1915.304288   80.109267  6.733610
印度      1146271    43203   2453.4   3210.843137  121.016807  6.872269
墨西哥      139613    10929    843.4   1173.218487   91.840336  7.087395
巴西       357136     8869    733.5   3536.000000   87.811881  7.262376
德国      2680983    95008   7428.4   2597.851744   92.062016  7.198062
意大利     2502215    77902   5377.3   3340.740988  104.008011  7.179306
日本     18000703   427792  36334.9   3564.495644   84.711287  7.195030
比利时      170987    11447   1003.3   1230.122302   82.352518  7.217986
法国     10213966   253169  20384.7   3627.118608   89.903764  7.238885
波兰       159577    14613   1347.0    881.640884   80.734807  7.441989
泰国      1564881    26002   1796.1   5322.724490   88.442177  6.109184
澳大利亚    1415713    25549   2093.4   4719.043333   85.163333  6.978000
瑞典       290113    27098   1432.0   1503.176166  140.404145  7.419689
美国    101806270  1081668  83217.4   8498.728608   90.297020  6.946940
英国     13249562   244005  20789.4   4797.089790   88.343592  7.526937
荷兰       144836    11685   1114.5    934.425806   75.387097  7.190323
西班牙     1486733    40455   3139.9   3326.024609   90.503356  7.024385
阿根廷      258271    10638    843.7   2226.474138   91.706897  7.273276
韩国      8761080   134734   8596.4   6484.885270   99.729090  6.362990

In [184]:
#汇总统计
pd.pivot_table(df, index=["产地"], aggfunc=[np.sum, np.mean], fill_value=0, margins=True)

            sum                             mean
           投票人数       时长        评分          投票人数          时长        评分
产地
中国台湾    5237466    53925    4367.2   8474.864078   87.257282  7.066667
中国大陆   41435441   309668   23067.9  10895.461741   81.427294  6.065711
中国香港   23285389   252431   18457.7   8167.446159   88.541214  6.474114
丹麦       394784    17444    1434.7   1993.858586   88.101010  7.245960
俄罗斯      486127    45753    3603.5   1019.134172   95.918239  7.554507
其他      3054119   167168   13895.9   1590.686979   87.066667  7.237448
加拿大     1384765    57919    4868.4   1915.304288   80.109267  6.733610
印度      1146271    43203    2453.4   3210.843137  121.016807  6.872269
墨西哥      139613    10929     843.4   1173.218487   91.840336  7.087395
巴西       357136     8869     733.5   3536.000000   87.811881  7.262376
德国      2680983    95008    7428.4   2597.851744   92.062016  7.198062
意大利     2502215    77902    5377.3   3340.740988  104.008011  7.179306
日本     18000703   427792   36334.9   3564.495644   84.711287  7.195030
比利时      170987    11447    1003.3   1230.122302   82.352518  7.217986
法国     10213966   253169   20384.7   3627.118608   89.903764  7.238885
波兰       159577    14613    1347.0    881.640884   80.734807  7.441989
泰国      1564881    26002    1796.1   5322.724490   88.442177  6.109184
澳大利亚    1415713    25549    2093.4   4719.043333   85.163333  6.978000
瑞典       290113    27098    1432.0   1503.176166  140.404145  7.419689
美国    101806270  1081668   83217.4   8498.728608   90.297020  6.946940
英国     13249562   244005   20789.4   4797.089790   88.343592  7.526937
荷兰       144836    11685    1114.5    934.425806   75.387097  7.190323
西班牙     1486733    40455    3139.9   3326.024609   90.503356  7.024385
阿根廷      258271    10638     843.7   2226.474138   91.706897  7.273276
韩国      8761080   134734    8596.4   6484.885270   99.729090  6.362990
All   239112335  3415081  264204.4   6264.733153   89.474979  6.922144

In [215]:
#对特定列进行数据统计
pd.pivot_table(df, index=["产地"], aggfunc={"投票人数":np.sum, "评分":np.mean}, fill_value=0)

           投票人数        评分
产地
中国台湾    5237466  7.066667
中国大陆   41435441  6.065711
中国香港   23285389  6.474114
丹麦       394784  7.245960
俄罗斯      486127  7.554507
其他      3054119  7.237448
加拿大     1384765  6.733610
印度      1146271  6.872269
墨西哥      139613  7.087395
巴西       357136  7.262376
德国      2680983  7.198062
意大利     2502215  7.179306
日本     18000703  7.195030
比利时      170987  7.217986
法国     10213966  7.238885
波兰       159577  7.441989
泰国      1564881  6.109184
澳大利亚    1415713  6.978000
瑞典       290113  7.419689
美国    101806270  6.946940
英国     13249562  7.526937
荷兰       144836  7.190323
西班牙     1486733  7.024385
阿根廷      258271  7.273276
韩国      8761080  6.362990

### 透视表的过滤

In [201]:
table = pd.pivot_table(df, index=["年代"], aggfunc={"投票人数":np.sum, "评分":np.mean}, fill_value=0)

In [202]:
type(table)

pandas.core.frame.DataFrame

In [216]:
table[:5]

      投票人数        评分
年代
1888   776  7.950000
1890    51  4.800000
1892   176  7.500000
1894   338  6.633333
1895  7679  7.575000

In [203]:
table.loc[1994]

投票人数    5.670752e+06
评分      7.262348e+00
Name: 1994, dtype: float64

In [207]:
table.sort_values(by="评分", ascending=False)

           投票人数        评分
年代
34943       128  9.900000
39180        49  8.900000
1924      10410  8.053571
1888        776  7.950000
1928      16193  7.945000
1912        761  7.920000
1923       7668  7.883333
1922      16876  7.804545
1925      27607  7.788000
1926      10203  7.773913
1916       7364  7.758333
1927      20163  7.751724
1921      16056  7.750000
1961     325057  7.744118
1952     128198  7.743678
1938      20976  7.736842
1962     282013  7.704895
1954     222385  7.702941
1945      48462  7.673469
1948     103226  7.657471
1950     169862  7.655263
1957     318173  7.652336
1949      57110  7.646067
1951      75532  7.636709
1936      87928  7.635000
1943      42342  7.615789
1946      61033  7.606780
1956     155027  7.600000
1937      77485  7.582000
1955     228130  7.580000
1965     324074  7.576074
1895       7679  7.575000
1959     220809  7.571875
1940     216401  7.571795
1960     189462  7.569466
1953     421178  7.567045
1909        293  7.560000
1942     138211  7.554717
1944      54398  7.538889
1958     108116  7.536885
1963     169316  7.536364
1964     201613  7.523077
1939     289681  7.520408
1934      39601  7.519608
1966     236195  7.518994
1935      40834  7.515217
1892        176  7.500000
1920       8911  7.492857
1919       3597  7.490000
1967     217763  7.484659
1902      11605  7.483333
1931      61684  7.483333
1947      32955  7.453333
1898       1157  7.450000
1929      25919  7.440000
1933      36486  7.430000
1941      72982  7.427660
1984     784149  7.375170
1911        960  7.375000
1969     122774  7.370048
1930      13877  7.360000
1906       1329  7.342857
1997    4426995  7.330168
1968     188550  7.317442
1983     426910  7.310108
1982     569966  7.297368
1979     426447  7.296035
1932      22203  7.294595
1970     128590  7.291053
1995    3976844  7.289366
1987    1073170  7.284548
1985     509774  7.280312
1972     475913  7.268116
1988    1876889  7.265729
1994    5670752  7.262348
1986     916472  7.261231
1915       6298  7.260000
1996    2634572  7.258801
1973     170422  7.250235
1901        658  7.250000
1998    4288143  7.238302
1900       1227  7.228571
1992    2386468  7.223678
1904       1567  7.212500
1989    1176806  7.210687
1918       4285  7.200000
1993    3579932  7.195692
1999    4460656  7.188000
1980     539321  7.186607
1981     440883  7.157299
1971     299703  7.155708
1991    1921186  7.154634
1977     210560  7.150685
1908       1553  7.150000
1990    1951476  7.149109
2003    7505258  7.137750
2000    4318580  7.134063
2001    7029519  7.110145
1976     312364  7.107725
1978     201366  7.096517
1917       1493  7.075000
1975     435657  7.071429
2002    5897334  7.069778
1974     375931  7.062332
1896       7874  7.037500
2004    9746963  7.031366
2005    8217218  7.030008
1907       1068  7.020000
1903       4730  6.968750
1910        526  6.940000
2006   11026565  6.914719
2008   13264254  6.913194
1899        142  6.900000
2007   10700316  6.875102
1913        529  6.862500
1905       1663  6.820000
2010   18048476  6.769867
2009   16229871  6.750000
1894        338  6.633333
1897        201  6.633333
2011   16351964  6.577010
1914       2728  6.473077
2012   14463052  6.458374
2013   15215050  6.392604
2014   14573872  6.259777
2015   12483522  6.141960
2016    1851413  5.868217
1890         51  4.800000
2008‎       544  2.700000

In [208]:
pd.pivot_table(df, index=["产地","年代"], aggfunc={"投票人数":np.sum, "评分":np.mean}, fill_value=0)

               投票人数        评分
产地   年代
中国台湾 1963       121  6.400000
     1965       461  6.800000
     1966        51  7.900000
     1967      4444  8.000000
     1968       178  7.400000
     1969       273  7.400000
     1970      5953  7.266667
     1971       153  6.933333
     1972       676  7.500000
     1973      4903  7.280000
     1974       815  6.771429
     1975      2214  6.611111
     1976      3189  6.336364
     1977      1761  6.525000
     1978      2618  6.800000
     1979      7887  6.956250
     1980      2200  7.222222
     1981      4143  7.140000
     1982      6199  6.942857
     1983     22919  7.750000
     1984      9558  7.410000
     1985     18207  7.314286
     1986     12628  7.418182
     1987     32262  7.550000
     1988     32186  6.877778
     1989     40547  7.857143
     1990     10338  6.900000
     1991    120202  7.100000
     1992     37466  7.600000
     1993    105238  6.840000
     1994    162341  7.428571
     1995     39361  6.938462
     1996     25499  7.900000
     1997      7882  7.300000
     1998     38080  7.350000
     1999      4067  6.411111
     2000    288300  7.466667
     2001     15735  7.355556
     2002    261857  7.680000
     2003      7162  7.450000
     2004     71071  7.285714
     2005    149199  7.047619
     2006    199001  6.982609
     2007    377112  6.968421
     2008    427524  7.420000
     2009    386512  7.100000
     2010    552455  7.053846
     2011    731501  7.231818
     2012    444104  6.556098
     2013    114066  7.076471
     2014     95478  6.522222
     2015    349369  6.576000
中国大陆 1905       137  8.400000
     1922      1600  8.100000
     1923        41  8.100000
     1926        84  6.900000
     1927       732  7.750000
     1928        69  7.400000
     1929       129  5.850000
     1931      1740  7.850000
     1932       153  7.400000
     1933      1000  7.575000
     1934     10044  7.742857
     1935      1650  7.575000
     1936       894  7.950000
     1937     13426  7.625000
     1938        49  6.900000
     1939       259  6.900000
     1940       703  7.600000
     1941      2026  7.050000
     1943        83  6.800000
     1947      9333  7.657143
     1948     18579  7.771429
     1949     11341  7.500000
     1950      4676  7.300000
     1951      1745  7.025000
     1952      4633  7.533333
     1953       802  7.100000
     1954      9021  7.675000
     1955     77289  7.687500
     1956     18435  7.776923
     1957      1069  7.450000
     1958     27456  7.630769
     1959     42176  7.540000
     1960     10421  7.628571
     1961    132208  7.662500
     1962     77091  7.993333
     1963     42509  7.800000
     1964     28290  7.478571
     1965     44280  7.083333
     1966       255  7.200000
     1970      1552  6.700000
     1971       856  7.650000
     1972       369  6.700000
     1973       296  6.300000
     1974     17094  6.500000
     1975       966  6.766667
     1976       310  7.025000
     1977       144  6.050000
     1978      1824  7.620000
     1979     74604  7.187500
     1980     80370  7.120833
     1981    201269  7.348148
     1982     97271  7.760714
     1983     81808  7.394737
     1984     28751  7.704545
     1985     15897  7.321739
     1986     60850  7.414286
     1987    107166  7.089655
     1988     72474  7.117857
     1989     22764  6.713333
     1990     60312  6.982353
     1991    109925  6.895000
     1992    116750  7.464000
     1993    539290  6.838710
     1994    466107  7.300000
     1995     83383  6.991304
     1996     82076  7.052174
     1997    279282  7.325000
     1998    133908  7.142105
     1999    379975  7.033333
     2000    424035  7.397500
     2001    444672  7.072973
     2002    599007  6.635897
     2003    647649  6.810256
     2004   1100800  6.700000
     2005   1068534  6.664384
     2006   1355795  6.507143
     2007   1231790  6.605691
     2008   1804494  6.616552
     2009   2149834  6.536628
     2010   3663756  6.357831
     2011   3710218  5.824606
     2012   3712472  5.727187
     2013   4916396  5.316667
     2014   4710358  4.963757
     2015   5320460  4.969189
     2016    860428  4.712000
     34943      128  9.900000
     2008‎      544  2.700000
中国香港 1935       101  6.500000
     1938        39  7.000000
     1939        47  6.500000
     1947       165  6.500000
     1948       628  6.600000
     1949       109  7.600000
     1950       274  6.925000
     1952        47  7.800000
     1953       240  7.150000
     1954       126  7.700000
     1955       816  6.950000
     1956       594  7.480000
     1957       291  7.350000
     1958       329  7.166667
     1959      2070  7.855556
     1960      2573  7.336364
     1961       660  7.033333
     1962      1097  7.285714
     1963      2623  7.220000
     1964      2819  7.120000
     1965      1456  6.892857
     1966      6091  6.628571
     1967      5540  6.495833
     1968      2606  6.452941
     1969      8164  6.503571
     1970      6203  6.561538
     1971     18257  6.360000
     1972     37389  6.560000
     1973     10562  6.374194
     1974     11277  6.432500
     1975     10880  6.445946
     1976     26347  6.600000
     1977     19878  6.531579
     1978     57300  6.634091
     1979     20632  6.750000
     1980     28410  6.666667
     1981     27940  6.716000
     1982     52765  6.632759
     1983    116754  6.837288
     1984    103660  6.691379
     1985    113874  6.598276
     1986    188439  6.614545
     1987    403003  6.798333
     1988    313086  6.679167
     1989    254258  6.628916
     1990    574916  6.621429
     1991    693666  6.477228
     1992    954938  6.420690
     1993   1374596  6.575439
     1994   1300511  6.698077
     1995   1234852  6.713889
     1996    853428  6.644737
     1997    557048  6.804762
     1998    539191  6.390769
     1999    854721  6.321053
     2000    573875  6.069737
     2001    787069  6.313580
     2002    934118  6.079452
     2003    655943  6.036842
     2004    592806  6.004918
     2005    554266  6.045714
     2006    330956  6.287805
     2007    836810  6.085106
     2008    902506  6.476786
     2009   1064941  6.442553
     2010   1950169  6.245455
     2011   1037921  5.971053
     2012    722035  6.110526
     2013    414461  6.105714
     2014    522649  5.616667
     2015    532269  5.589189
     2016     74309  5.390909
丹麦   1919        57  7.700000
     1921        91  8.200000
     1922       687  7.850000
     1925        87  6.900000
     1942        33  5.900000
     1943       765  8.500000
     1946        43  6.300000
     1947        47  6.900000
     1948        50  6.800000
     1949        32  6.800000
     1950        33  6.100000
     1955       781  8.400000
     1964       559  8.200000
     1966       362  8.400000
     1967       175  7.900000
     1970       486  5.966667
     1973      1028  5.700000
     1978       650  7.700000
     1980       234  6.600000
     1981        52  8.100000
     1983      1142  8.000000
     1984      1023  7.550000
     1987      4663  7.800000
     1988       239  7.400000
     1991      1765  8.700000
     1992       348  7.950000
     1993        72  6.100000
     1994       803  7.833333
     1995       186  7.700000
     1996      9035  8.066667
     1997      2041  7.450000
     1998      4091  7.525000
     1999      2793  6.960000
     2000     62668  7.800000
     2001       735  7.466667
     2002      3055  7.340000
     2003     54558  7.644444
     2004      1823  7.214286
...             ...       ...
英国   1931       479  6.200000
     1932        55  6.600000
     1933       158  7.500000
     1934      1255  7.275000
     1935      9091  7.650000
     1936      3497  7.460000
     1937      2286  6.800000
     1938      5118  7.850000
     1939      1091  7.025000
     1940      1438  7.050000
     1941      1885  7.200000
     1942       227  7.066667
     1943       270  8.100000
     1944       768  6.860000
     1945      5508  7.560000
     1946      2746  7.600000
     1947      1459  7.566667
     1948     14026  7.983333
     1949     11375  7.428571
     1950      3111  7.325000
     1951      6139  7.450000
     1952      1623  7.675000
     1954     22077  7.863636
     1955      3635  7.525000
     1956       685  7.700000
     1957     15082  7.287500
     1958      2968  6.912500
     1959      2214  7.337500
     1960      5691  7.300000
     1961      2985  7.688889
     1962     26684  7.440000
     1963     33211  7.381818
     1964     14151  7.478571
     1965     17776  7.542105
     1966     21119  7.372727
     1967     13781  7.447059
     1968     20162  7.728571
     1969     10326  7.600000
     1970     11256  7.607143
     1971    197068  7.357692
     1972      7562  7.783333
     1973      9717  7.490000
     1974     33604  7.622222
     1975     23601  7.550000
     1976      9938  7.161538
     1977      6220  7.388889
     1978     49214  7.678571
     1979     83993  7.336842
     1980    103208  7.437500
     1981     38357  7.214286
     1982     70225  8.116667
     1983     34052  7.621739
     1984     47220  8.059091
     1985     48178  7.803571
     1986     19846  8.042857
     1987     96401  7.851515
     1988     12110  7.703125
     1989     23858  7.724138
     1990     16765  7.610526
     1991     15067  7.794595
     1992     44844  7.693333
     1993     33227  7.988462
     1994     92585  7.828947
     1995     84197  7.887500
     1996    243742  7.814634
     1997    140013  7.746341
     1998    551891  7.761818
     1999    272170  7.772973
     2000    450180  7.772727
     2001    287734  7.689655
     2002    234066  7.370492
     2003    507426  7.680597
     2004    546348  7.535870
     2005    742235  7.497727
     2006    468656  7.580412
     2007    795706  7.459459
     2008   1148327  7.584783
     2009   1140428  7.381379
     2010    777260  7.571613
     2011    601011  7.343284
     2012    549995  7.293103
     2013    490998  7.448322
     2014   1005905  7.275000
     2015    627429  7.155056
     2016    160680  7.200000
荷兰   1911        65  6.400000
     1928       306  7.500000
     1929      1400  8.400000
     1931        55  8.000000
     1958       160  8.700000
     1962        33  8.500000
     1971      1513  6.200000
     1973      4639  7.400000
     1974       317  7.200000
     1975        83  6.600000
     1977       908  7.300000
     1980       144  8.100000
     1981        47  8.200000
     1983      2631  6.800000
     1984      6681  8.150000
     1985       194  5.600000
     1986       427  7.933333
     1987       101  6.200000
     1988      2920  7.050000
     1990        30  7.500000
     1991       184  7.700000
     1992      7031  7.900000
     1994      1084  7.650000
     1995      1289  7.825000
     1996       145  7.750000
     1997       850  6.750000
     1998       696  7.700000
     1999       185  7.600000
     2000       285  9.200000
     2001        48  6.800000
     2002       507  7.500000
     2003       660  7.600000
     2004       402  7.300000
     2005      1426  6.925000
     2006     38689  7.387500
     2007      2414  7.142857
     2008      8304  7.515385
     2009     24379  6.736364
     2010      4781  6.970000
     2011      2985  6.622222
     2012      2863  6.766667
     2013      8239  6.563636
     2014      9861  7.300000
     2015      4875  6.700000
西班牙  1908       110  8.100000
     1933       772  7.900000
     1953        67  8.000000
     1955       653  8.200000
     1961      2048  7.650000
     1963        92  7.600000
     1965       116  8.000000
     1966       131  7.800000
     1967       196  7.350000
     1968       142  6.150000
     1969        76  7.700000
     1970       168  6.900000
     1971       196  6.550000
     1972      4844  8.300000
     1973      2687  7.000000
     1974       310  7.350000
     1976      3081  7.366667
     1978       232  6.200000
     1979       120  5.600000
     1980       716  6.500000
     1981       397  8.300000
     1982       857  7.200000
     1983      4212  7.925000
     1984      1190  7.933333
     1985       233  6.750000
     1986      2355  7.250000
     1987      3892  7.400000
     1988      3604  7.133333
     1989       115  7.000000
     1990     16920  7.050000
     1991      6040  7.160000
     1992      9771  7.750000
     1993      7441  7.133333
     1994      9349  6.900000
     1995      3161  7.500000
     1996      5769  7.487500
     1997     16533  7.450000
     1998     12390  7.277778
     1999     38614  7.190909
     2000      6717  7.376923
     2001     27233  6.714286
     2002     80405  7.194118
     2003      8223  7.415789
     2004    105367  7.215789
     2005     11676  6.848000
     2006    139997  7.080000
     2007    121745  7.100000
     2008    185374  7.013636
     2009    106550  6.875000
     2010    100721  6.933333
     2011    257667  6.742857
     2012     85813  6.595238
     2013     45473  6.358333
     2014     29319  6.868750
     2015     14853  6.514286
阿根廷  1958       176  7.500000
     1965        44  7.400000
     1968       138  8.900000
     1969        62  8.400000
     1984        25  7.200000
     1985       627  8.000000
     1986       871  7.800000
     1988       400  8.100000
     1989        88  9.600000
     1992      1836  8.100000
     1994      1635  5.600000
     1997       124  7.800000
     1998       732  7.650000
     1999        84  7.350000
     2000      9506  8.000000
     2001       452  7.175000
     2002       458  7.800000
     2003      1131  7.400000
     2004     30784  7.420000
     2005      2767  7.175000
     2006      1897  7.085714
     2007      1501  6.866667
     2008     51780  7.150000
     2009     52038  7.371429
     2010       355  6.900000
     2011     12060  7.350000
     2012       506  6.483333
     2013      6341  6.616667
     2014     79107  7.150000
     2015       746  7.233333
韩国   1960      1521  6.800000
     1961        89  8.000000
     1975       170  7.100000
     1981       143  7.400000
     1984        95  6.000000
     1985        78  8.600000
     1986       109  6.600000
     1987       774  5.700000
     1989       406  7.950000
     1990       132  7.350000
     1991       281  6.100000
     1992       225  6.850000
     1993      1338  7.460000
     1994       195  6.666667
     1995      1321  6.600000
     1996      3587  6.985714
     1997     11047  6.778571
     1998     66664  6.852941
     1999     53573  6.834783
     2000    140652  6.383333
     2001    354597  6.709091
     2002    249115  6.641667
     2003    853007  6.814545
     2004    608902  6.814062
     2005    469217  6.830137
     2006    656011  6.737500
     2007    286484  6.625000
     2008    511254  6.744000
     2009    342280  6.505479
     2010    762798  6.459551
     2011    805446  6.365556
     2012    610829  6.064151
     2013   1130983  6.098198
     2014    453152  5.650833
     2015    349808  5.423853
     2016     34797  5.730000

[1587 rows x 2 columns]